export interface Composition {
  /** ID (auto-generated by database) */
  id?: string

  /** Human-readable name. */
  name: string

  /** Optional human-readable description. */
  description?: string
}

export type CompositionCollection = Composition[]
